=== cubastion-umesh/cubnbrm/brmadmin/brm/xsd/pin_config_rtp_trim_flist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
        <xs:element name="RTPTrimFlistConfiguration">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element name="EventMapList" type="EventMapListType"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="Type" type="xs:string"/>
        <xs:element name="Flags" type="xs:string"/>
        <xs:complexType name="EventType">
                <xs:all>
                        <xs:element ref="Type"/>
                        <xs:element ref="Flags"/>
                </xs:all>
        </xs:complexType>
        <xs:complexType name="RequiredFieldType">
                <xs:all>
                        <xs:element ref="Name"/>
                </xs:all>
                <xs:sequence>
                        <xs:element name="RequiredField" type="RequiredFieldType" maxOccurs="unbounded"/>
                </xs:sequence>
        </xs:complexType>
        <xs:complexType name="EventMapType">
                <xs:sequence>
                        <xs:element name="Event" type="EventType" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:sequence>
                        <xs:element name="RequiredField" type="RequiredFieldType" maxOccurs="unbounded"/>
                </xs:sequence>
        </xs:complexType>
        <xs:complexType name="EventMapListType">
                <xs:sequence>
                        <xs:element name="EventMap" type="EventMapType" maxOccurs="unbounded"/>
                </xs:sequence>
        </xs:complexType>
</xs:schema>

=== cubastion-umesh/cubnbrm/brmadmin/brm/sys/data/config/pin_config_rtp_trim_flist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
================================================================
Copyright (c) 2005 - 2006 Oracle. All rights reserved.

This material is the confidential property of Oracle Corporation or its licensors 
and may be used, reproduced, stored or transmitted only in accordance with a valid 
Oracle license or sublicense agreement.

67FP2:09272004:CO 129232- Integrated trim flist for rating + discounting
================================================================
-->

<RTPTrimFlistConfiguration xmlns="http://www.portal.com/InfranetXMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.portal.com/InfranetXMLSchema pin_config_rtp_trim_flist.xsd">
  <EventMapList>
    <EventMap>
      <Event>
        <Type>/event/session</Type>
        <Flags>0</Flags>
      </Event>
      <Event>
        <Type>/event/session/</Type>
        <Flags>1</Flags>
      </Event>
      <Event>
        <Type>*</Type>
        <Flags>1</Flags>
      </Event>
      <RequiredField>
        <Name>PIN_FLD_POID</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_CHECK_CREDIT_LIMIT</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_SERVICE_CLASS</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_ANI</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_DN</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_ZONEMAP_NAME</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_IMPACT_TYPE</Name>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_EVENT</Name>
        <RequiredField>
          <Name>PIN_FLD_POID</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_NAME</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_PROGRAM_NAME</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_START_T</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_END_T</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_PROFILE_LABEL_LIST</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_UNRATED_QUANTITY</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_ACCOUNT_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_TIME_OFFSET</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_USAGE_TYPE</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_SERVICE_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_BAL_GRP_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_BILLINFO_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_RUM_NAME</Name>
        </RequiredField>
	<RequiredField>
          <Name>PIN_FLD_MOST_CALLED_INFO</Name>
          <RequiredField>
            <Name>PIN_FLD_MOST_CALLED_LIST</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_AMOUNT</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_QUANTITY</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_COUNT</Name>
          </RequiredField>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_GSM_INFO</Name>
          <RequiredField>
            <Name>PIN_FLD_CALLED_NUM_MODIF_MARK</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_DIRECTION</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_CELL_ID</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_SUB_TRANS_ID</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_NUMBER_OF_UNITS</Name>
          </RequiredField>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_TELCO_INFO</Name>
          <RequiredField>
            <Name>PIN_FLD_CALLING_FROM</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_SVC_TYPE</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_SVC_CODE</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_CALLED_TO</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_USAGE_CLASS</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_TERMINATE_CAUSE</Name>
          </RequiredField>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_GPRS_INFO</Name>
          <RequiredField>
            <Name>PIN_FLD_ANONYMOUS_LOGIN</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_MSISDN</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_BYTES_IN</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_BYTES_OUT</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_NUMBER_OF_UNITS</Name>
          </RequiredField>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_BAL_IMPACTS</Name>
          <RequiredField>
            <Name>PIN_FLD_AMOUNT</Name>
          </RequiredField>
	  <RequiredField>
            <Name>PIN_FLD_AMOUNT_DEFERRED</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_RESOURCE_ID</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_GL_ID</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_IMPACT_TYPE</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_IMPACT_CATEGORY</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_QUANTITY</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_RATE_TAG</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_TAX_CODE</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_RUM_ID</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_QUANTITY_FROM</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_QUANTITY_TO</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_SUB_BALANCES</Name>
            <RequiredField>
              <Name>PIN_FLD_VALID_FROM</Name>
            </RequiredField>
            <RequiredField>
              <Name>PIN_FLD_VALID_TO</Name>
            </RequiredField>
            <RequiredField>
              <Name>PIN_FLD_RELATIVE_CYCLE_OFFSET</Name>
            </RequiredField>
          </RequiredField>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_RUM_MAP</Name>
          <RequiredField>
            <Name>PIN_FLD_RUM_NAME</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_NET_QUANTITY</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_UNRATED_QUANTITY</Name>
          </RequiredField>
        </RequiredField>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_DISCOUNTS</Name>
        <RequiredField>
          <Name>PIN_FLD_ACCOUNT_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_OWNER_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_BAL_GRP_OBJ</Name>
        </RequiredField>
        <RequiredField>
          <Name>PIN_FLD_DISCOUNT_LIST</Name>
          <RequiredField>
            <Name>PIN_FLD_DISCOUNT_OBJ</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_NODE_LOCATION</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_PURCHASE_END_T</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_PURCHASE_START_T</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_QUANTITY</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_STATUS</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_USAGE_END_T</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_USAGE_START_T</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_FLAGS</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_TYPE</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_CYCLE_FEE_FLAGS</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_SCALE</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_FIRST_USAGE</Name>
          </RequiredField>
        </RequiredField>
      </RequiredField>
      <RequiredField>
        <Name>PIN_FLD_PERIOD</Name>
        <RequiredField>
          <Name>PIN_FLD_DISCOUNTS</Name>
          <RequiredField>
            <Name>PIN_FLD_ACCOUNT_OBJ</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_OWNER_OBJ</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_BAL_GRP_OBJ</Name>
          </RequiredField>
          <RequiredField>
            <Name>PIN_FLD_DISCOUNT_LIST</Name>
            <RequiredField>
              <Name>PIN_FLD_DISCOUNT_OBJ</Name>
            </RequiredField>
            <RequiredField>
              <Name>PIN_FLD_NODE_LOCATION</Name>
            </RequiredField>
            <RequiredField>
              <Name>PIN_FLD_PURCHASE_END_T</Name>
            </RequiredField>
            <RequiredField>
              <Name>PIN_FLD_PURCHASE_START_T</Name>
            </RequiredField>
            <RequiredField>
