=== cubastion-umesh/cubnbrm/brmadmin/brm/xsd/pin_rerate_flds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.portal.com/PortalXMLSchema" xmlns="http://www.portal.com/PortalXMLSchema"
xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="value" type="xs:string"/>
	<xs:complexType name="PinRerateType">
		<xs:all>
			<xs:element ref="Name"/>
			<xs:element ref="value"/>
		</xs:all>
	</xs:complexType>
        <xs:element name="PinRerate_flds">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element name="PinRerate" type="PinRerateType" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
	<xs:complexType name="RerateCompareBalImpactsType">
		<xs:all>
			<xs:element ref="Name"/>
		</xs:all>
	</xs:complexType>
        <xs:element name="RerateCompareBalImpacts_flds">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element name="RerateCompareBalImpacts" type="RerateCompareBalImpactsType" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
</xs:schema>

=== cubastion-umesh/cubnbrm/brmadmin/brm/sys/data/config/pin_rerate_compare_bi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
================================================================
 Copyright (c) 2005, 2008, Oracle and/or its affiliates. All rights reserved.

This material is the confidential property of Oracle Corporation
or its licensors and may be used, reproduced, stored or transmitted
only in accordance with a valid Oracle license or sublicense agreement.
================================================================
-->
<RerateCompareBalImpacts_flds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.portal.com/PortalXMLSchema" xsi:schemaLocation="http://www.portal.com/PortalXMLSchema ../../../xsd/pin_rerate_flds.xsd">

	<RerateCompareBalImpacts>
		<Name>PIN_FLD_RESOURCE_ID</Name>
	</RerateCompareBalImpacts>
	<RerateCompareBalImpacts>
		<Name>PIN_FLD_BAL_GRP_OBJ</Name>
	</RerateCompareBalImpacts>
	<RerateCompareBalImpacts>
		<Name>PIN_FLD_GL_ID</Name>
	</RerateCompareBalImpacts>
	<RerateCompareBalImpacts>
		<Name>PIN_FLD_TAX_CODE</Name>
	</RerateCompareBalImpacts>
	<RerateCompareBalImpacts>
		<Name>PIN_FLD_PRODUCT_OBJ</Name>
	</RerateCompareBalImpacts>
</RerateCompareBalImpacts_flds>

=== cubastion-umesh/cubnbrm/brmadmin/brm/sys/data/config/pin_rerate_flds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
================================================================
 Copyright (c) 2005, 2009, Oracle and/or its affiliates. All rights reserved. 

This material is the confidential property of Oracle Corporation
or its licensors and may be used, reproduced, stored or transmitted
only in accordance with a valid Oracle license or sublicense agreement.
================================================================
-->
<PinRerate_flds xmlns="http://www.portal.com/PortalXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.portal.com/PortalXMLSchema ../../../xsd/pin_rerate_flds.xsd">
	<PinRerate>
		<Name>EVENT.PIN_FLD_START_T</Name>
		<value>startTime</value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_END_T</Name>
		<value>endTime</value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_BAL_IMPACTS.PIN_FLD_IMPACT_CATEGORY</Name>
		<value>impactCategory </value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_ITEM_OBJ</Name>
		<value>itemObject</value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_DEAL</Name>
		<value>deal</value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_SERVICE_OBJ</Name>
		<value>service</value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_BAL_IMPACTS.PIN_FLD_PRODUCT_OBJ</Name>
		<value>product</value>
	</PinRerate>
	<PinRerate>
		<Name>EVENT.PIN_FLD_TELCO_INFO.PIN_FLD_CALLED_TO</Name>
		<value>DestinationNumber</value>
	</PinRerate>
</PinRerate_flds>
