=== cubastion-umesh/cubnbrm/brmadmin/brm/xsd/pin_config_ood_criteria.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema 
	targetNamespace="http://www.portal.com/schemas/BusinessConfig"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:businessConfig="http://www.portal.com/schemas/BusinessConfig"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	
	<xs:annotation>
		<xs:documentation xml:lang="en">
			Copyright (c) 2006 Oracle. All rights reserved.
			This material is the confidential property of Oracle Corporation 
			or its licensors and may be used, reproduced, stored or transmitted
			only in accordance with a valid Oracle license or sublicense agreement.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="OodCriteriaConfiguration" type="businessConfig:OodCriteriaConfigurationType" />

	<xs:complexType name="OodCriteriaConfigurationType">
	  <xs:sequence>
	    <xs:element name="OodCriteriaElement" type="businessConfig:OodCriteriaElementType" 
			      minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
	</xs:complexType>

	<xs:complexType name="OodCriteriaElementType">
	  <xs:sequence>
	    <xs:element name="CriteriaName" type="businessConfig:CriteriaNameType" maxOccurs="1"/>
	    <xs:element name="ParameterList" type="businessConfig:ParameterListType" maxOccurs="1"/>
          </xs:sequence>
	</xs:complexType>

	<xs:complexType name="ParameterListType" >
	  <xs:sequence>
	    <xs:element name="Parameter" type="businessConfig:ParameterType" 
			minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ParameterType" >
          <xs:simpleContent>
            <xs:extension  base="xs:string">
              <xs:attribute name="Type" type="businessConfig:ParamValueType"/>
            </xs:extension>
           </xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="ParamValueType">
          <xs:restriction base="xs:string">
	    <xs:pattern value="Service|Event|Product|Discount"/>
	  </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="CriteriaNameType">
          <xs:restriction base="xs:string">
	    <xs:minLength value="1"/>
	  </xs:restriction>
	</xs:simpleType>

</xs:schema>

=== cubastion-umesh/cubnbrm/brmadmin/brm/sys/data/config/pin_config_ood_criteria.xml
<?xml version="1.0" encoding="UTF-8"?>

<OodCriteriaConfiguration
	xmlns="http://www.portal.com/schemas/BusinessConfig" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.portal.com/schemas/BusinessConfig /apps/brm/brmadmin/brm/xsd/pin_config_ood_criteria.xsd">

	<!-- This file is a sample file. -->
	<!-- This file needs to be modified based on the out-of-order configuration required -->
	<!-- for an installation. THIS FILE SHOULD NOT BE LOADED WITH THE DATA SUPPLIED HERE.-->
	  <OodCriteriaElement>
      	    <CriteriaName>TEL_SERVICE</CriteriaName>
      	    <ParameterList>
      	    <Parameter Type="Service">/service/gsm/telephony</Parameter>
      	    <Parameter Type="Event">/event/delayed/session/gsm/telephony</Parameter>
      	    </ParameterList>
          </OodCriteriaElement>
	  <OodCriteriaElement>
      	    <CriteriaName>GSM_SERVICE</CriteriaName>
      	    <ParameterList>
      	    <Parameter Type="Service">/service/telco/gsm</Parameter>
      	    <Parameter Type="Event">/event/delayed/session/telco/gsm/telephony</Parameter>
      	    </ParameterList>
          </OodCriteriaElement>
	  <OodCriteriaElement>
      	    <CriteriaName>A_MULTI_TEL_SERVICE</CriteriaName>
      	    <ParameterList>
      	    <Parameter Type="Service">/service/tel</Parameter>
      	    <Parameter Type="Event">/event/session/tel</Parameter>
      	    <Parameter Type="Product">Tel product</Parameter>
      	    <Parameter Type="Discount">Tel discount</Parameter>
      	    </ParameterList>
          </OodCriteriaElement>
</OodCriteriaConfiguration>
